spring.application.name=order

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ordermanager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1312}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

logging.level.root=INFO
logging.file.name=logs/application.log

security.jwt.secret=${JWT_SECRET:minhaChaveSuperSecretaParaJwtComMaisDe32Caracteres123}
security.jwt.expiration=${JWT_EXPIRATION:3600000}

management.endpoints.web.exposure.include=health,info,metrics,prometheus,logfile
management.endpoint.health.show-details=always
management.endpoint.logfile.external-file=logs/application.log
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=order-manager
management.info.env.enabled=true

info.app.name=Order Manager API
info.app.description=API REST para gerenciamento de pedidos
info.app.version=1.0.0