spring.application.name=order

spring.datasource.url=jdbc:postgresql://localhost:5432/ordermanager
spring.datasource.username=postgres
spring.datasource.password=1312

logging.level.root=INFO
security.jwt.secret=minhaChaveSuperSecretaParaJwtComMaisDe32Caracteres123
security.jwt.expiration=3600000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true