spring.application.name=order

spring.datasource.url=jdbc:postgresql://localhost:5432/ordermanager
spring.datasource.username=postgres
spring.datasource.password=1312

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.level.root=INFO
logging.file.name=logs/application.log

security.jwt.secret=minhaChaveSuperSecretaParaJwtComMaisDe32Caracteres123
security.jwt.expiration=3600000

management.endpoints.web.exposure.include=health,info,metrics,prometheus,logfile
management.endpoint.health.show-details=always
management.endpoint.logfile.external-file=logs/application.log
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=order-manager
management.info.env.enabled=true

info.app.name=Order Manager API
info.app.description=API REST para gerenciamento de pedidos
info.app.version=1.0.0